import GNB from '@/components/commons/GNB';
import AppProviders from '@/providers/AppProviders';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const pretendard = localFont({
	src: '../fonts/PretendardVariable.woff2',
	display: 'swap',
	weight: '45 920',
	variable: '--font-pretendard'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${pretendard.variable} antialiased`}>
				<AppProviders>
					{/* TODO: 공통 디자인 뽑기 */}
					<div className="box-border flex min-h-screen w-full flex-col bg-gray-900">
						<GNB />
						{children}
					</div>
				</AppProviders>
			</body>
		</html>
	);
}
